### ISSUE TITLE
`scoping.keep()`: not sure how it works?

### ISSUE THREAD

**Issue by mpettis** [l74d/scoping#1]
Could you provide a working example of how to use `scoping.keep()` in the README.md?

**Comment by mpettis** [comment]
Nevermind, I can't read...

**Comment by l74d** [comment]
Just in case anyone else searched and ended up on this page:

```
with scoping():
    b = 4
    scoping.keep('b')  #The name of the variable to be "kept" needs to be passed as a string to keep() 
assert(4 == b)
```

I wish it could be 
```
scoping.keep(b)
```
without the quotes, but I am yet to find out a simple way to do that.
